
package ec.edu.espe.CraftStoreInventorySystem.view;

import ec.edu.espe.CraftStoreInventory.model.Product;
import ec.edu.espe.CraftStoreInventory.utils.CloudDB;
import java.awt.Color;
import javax.swing.JOptionPane;

public class FrmAddProduct extends javax.swing.JFrame {

    int xMouse, yMouse;
    
    public FrmAddProduct() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backGround = new javax.swing.JPanel();
        addBtn = new javax.swing.JPanel();
        addBtnText = new javax.swing.JLabel();
        returnBtn = new javax.swing.JPanel();
        returnBtnText = new javax.swing.JLabel();
        addTitle = new javax.swing.JLabel();
        idText = new javax.swing.JLabel();
        nameText = new javax.swing.JLabel();
        descriptionText = new javax.swing.JLabel();
        categoryText = new javax.swing.JLabel();
        priceText = new javax.swing.JLabel();
        sizeText = new javax.swing.JLabel();
        quantityText = new javax.swing.JLabel();
        idFldText = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        nameFldText = new javax.swing.JTextField();
        quantityFldText = new javax.swing.JTextField();
        descriptionFldText = new javax.swing.JTextField();
        categoryFldText = new javax.swing.JTextField();
        priceFldText = new javax.swing.JTextField();
        sizeFldText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backGround.setBackground(new java.awt.Color(255, 255, 255));
        backGround.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addBtn.setBackground(new java.awt.Color(110, 80, 159));
        addBtn.setPreferredSize(new java.awt.Dimension(160, 50));

        addBtnText.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        addBtnText.setForeground(new java.awt.Color(255, 255, 255));
        addBtnText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addBtnText.setText("AÑADIR");
        addBtnText.setToolTipText("");
        addBtnText.setAutoscrolls(true);
        addBtnText.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addBtnText.setPreferredSize(new java.awt.Dimension(160, 50));
        addBtnText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addBtnTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addBtnTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addBtnTextMouseExited(evt);
            }
        });

        javax.swing.GroupLayout addBtnLayout = new javax.swing.GroupLayout(addBtn);
        addBtn.setLayout(addBtnLayout);
        addBtnLayout.setHorizontalGroup(
            addBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addBtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(addBtnText, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        addBtnLayout.setVerticalGroup(
            addBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addBtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(addBtnText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        backGround.add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, 140, 40));

        returnBtn.setBackground(new java.awt.Color(110, 80, 159));
        returnBtn.setPreferredSize(new java.awt.Dimension(160, 50));

        returnBtnText.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        returnBtnText.setForeground(new java.awt.Color(255, 255, 255));
        returnBtnText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        returnBtnText.setText("REGRESAR");
        returnBtnText.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        returnBtnText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                returnBtnTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                returnBtnTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                returnBtnTextMouseExited(evt);
            }
        });

        javax.swing.GroupLayout returnBtnLayout = new javax.swing.GroupLayout(returnBtn);
        returnBtn.setLayout(returnBtnLayout);
        returnBtnLayout.setHorizontalGroup(
            returnBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(returnBtnText, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        returnBtnLayout.setVerticalGroup(
            returnBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(returnBtnText, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        backGround.add(returnBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 430, 140, 40));

        addTitle.setFont(new java.awt.Font("Roboto Black", 1, 30)); // NOI18N
        addTitle.setForeground(new java.awt.Color(255, 255, 255));
        addTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addTitle.setText("AÑADIR PRODUCTO");
        backGround.add(addTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 340, 40));

        idText.setFont(new java.awt.Font("Roboto Medium", 3, 15)); // NOI18N
        idText.setText("Id:");
        backGround.add(idText, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, -1, -1));

        nameText.setFont(new java.awt.Font("Roboto Medium", 3, 15)); // NOI18N
        nameText.setText("Nombre:");
        backGround.add(nameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, -1, -1));

        descriptionText.setFont(new java.awt.Font("Roboto Medium", 3, 15)); // NOI18N
        descriptionText.setText("Descripción:");
        backGround.add(descriptionText, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, -1, -1));

        categoryText.setFont(new java.awt.Font("Roboto Medium", 3, 15)); // NOI18N
        categoryText.setText("Categoría:");
        backGround.add(categoryText, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, -1, -1));

        priceText.setFont(new java.awt.Font("Roboto Medium", 3, 15)); // NOI18N
        priceText.setText("Precio:");
        backGround.add(priceText, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, -1, -1));

        sizeText.setFont(new java.awt.Font("Roboto Medium", 3, 15)); // NOI18N
        sizeText.setText("Tamaño:");
        backGround.add(sizeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, -1, -1));

        quantityText.setFont(new java.awt.Font("Roboto Medium", 3, 15)); // NOI18N
        quantityText.setText("Cantidad:");
        backGround.add(quantityText, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, -1, -1));

        idFldText.setBorder(null);
        idFldText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                idFldTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                idFldTextMouseExited(evt);
            }
        });
        idFldText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                idFldTextKeyReleased(evt);
            }
        });
        backGround.add(idFldText, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 130, -1));

        jSeparator1.setForeground(new java.awt.Color(69, 32, 130));
        backGround.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 130, -1));

        jSeparator2.setForeground(new java.awt.Color(69, 32, 130));
        backGround.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, 280, 10));

        jSeparator3.setForeground(new java.awt.Color(69, 32, 130));
        backGround.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 280, 10));

        jSeparator4.setForeground(new java.awt.Color(69, 32, 130));
        backGround.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 280, 10));

        jSeparator5.setForeground(new java.awt.Color(69, 32, 130));
        backGround.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 280, 10));

        jSeparator6.setForeground(new java.awt.Color(69, 32, 130));
        backGround.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 280, 10));

        jSeparator7.setForeground(new java.awt.Color(69, 32, 130));
        backGround.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, 280, 10));

        nameFldText.setBorder(null);
        backGround.add(nameFldText, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 280, -1));

        quantityFldText.setBorder(null);
        backGround.add(quantityFldText, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, 280, -1));

        descriptionFldText.setBorder(null);
        backGround.add(descriptionFldText, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 280, -1));

        categoryFldText.setBorder(null);
        backGround.add(categoryFldText, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 280, -1));

        priceFldText.setBorder(null);
        backGround.add(priceFldText, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 280, -1));

        sizeFldText.setBorder(null);
        backGround.add(sizeFldText, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 280, -1));

        jLabel2.setFont(new java.awt.Font("Roboto Thin", 2, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Ingrese un 0 al inicio, luego el número de producto");
        backGround.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, 290, -1));

        jPanel1.setBackground(new java.awt.Color(221, 137, 213));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        backGround.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backGround, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backGround, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBtnTextMouseEntered
        addBtn.setBackground(new Color(174, 58, 166));
    }//GEN-LAST:event_addBtnTextMouseEntered

    private void returnBtnTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnBtnTextMouseEntered
        returnBtn.setBackground(new Color(174, 58, 166));
    }//GEN-LAST:event_returnBtnTextMouseEntered

    private void addBtnTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBtnTextMouseExited
        addBtn.setBackground(new Color(110, 80, 159));
    }//GEN-LAST:event_addBtnTextMouseExited

    private void returnBtnTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnBtnTextMouseExited
        returnBtn.setBackground(new Color(110, 80, 159));
    }//GEN-LAST:event_returnBtnTextMouseExited

    private void returnBtnTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnBtnTextMouseClicked
        FrmUniversoDelFomix frmUniversoDelFomix = new FrmUniversoDelFomix();
        this.setVisible(false);
        frmUniversoDelFomix.setVisible(true);
    }//GEN-LAST:event_returnBtnTextMouseClicked

    private void idFldTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_idFldTextMouseEntered
        jLabel2.setVisible(true);
    }//GEN-LAST:event_idFldTextMouseEntered

    private void idFldTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_idFldTextMouseExited
        jLabel2.setVisible(false);
    }//GEN-LAST:event_idFldTextMouseExited

    private void idFldTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idFldTextKeyReleased
        String id = idFldText.getText();
        if (!id.matches("\\d*")) {
            JOptionPane.showMessageDialog(this, "El campo ID solo puede contener números", "Entrada inválida", JOptionPane.WARNING_MESSAGE);
            idFldText.setText(id.replaceAll("[^\\d]", ""));
        } else if (!id.startsWith("0")) {
            JOptionPane.showMessageDialog(this, "El ID debe comenzar con un 0", "Falta 0 al inicio", JOptionPane.WARNING_MESSAGE);
            idFldText.setText("");
}
    }//GEN-LAST:event_idFldTextKeyReleased

    private void addBtnTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBtnTextMouseClicked
        String id = idFldText.getText();
        String name = nameFldText.getText();
        String description = descriptionFldText.getText();
        String quantityString = quantityFldText.getText(); // Obtén el valor como String
        String category = categoryFldText.getText();
        String priceString = priceFldText.getText(); // Obtén el valor como String
        String size = sizeFldText.getText();

    // Convertir los valores a los tipos apropiados
    int quantity;
    float price;

    try {
        quantity = Integer.parseInt(quantityString); // Convertir a int
    } catch (NumberFormatException e) {
        quantity = 0; // Manejar el error de conversión si el valor no es un entero válido
        JOptionPane.showMessageDialog(this, "Cantidad no válida. Se usará 0.", "Advertencia", JOptionPane.WARNING_MESSAGE);
    }

    try {
        price = Float.parseFloat(priceString); // Convertir a float
    } catch (NumberFormatException e) {
        price = 0.0f; // Manejar el error de conversión si el valor no es un float válido
        JOptionPane.showMessageDialog(this, "Precio no válido. Se usará 0.0.", "Advertencia", JOptionPane.WARNING_MESSAGE);
    }

    // Crear el objeto Product
    Product product = new Product(id, name, description, quantity, category, price, size);

    // Guardar el producto en la base de datos
    CloudDB cloudDB = new CloudDB();
    
    try {
        if (cloudDB.productExists(id)) {
            cloudDB.updateProduct(product);
            JOptionPane.showMessageDialog(this, "Producto actualizado exitosamente!");
        } else {
            cloudDB.uploadProductData(product);
            JOptionPane.showMessageDialog(this, "Producto añadido exitosamente!");
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al añadir producto: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_addBtnTextMouseClicked
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAddProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addBtn;
    private javax.swing.JLabel addBtnText;
    private javax.swing.JLabel addTitle;
    private javax.swing.JPanel backGround;
    private javax.swing.JTextField categoryFldText;
    private javax.swing.JLabel categoryText;
    private javax.swing.JTextField descriptionFldText;
    private javax.swing.JLabel descriptionText;
    private javax.swing.JTextField idFldText;
    private javax.swing.JLabel idText;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextField nameFldText;
    private javax.swing.JLabel nameText;
    private javax.swing.JTextField priceFldText;
    private javax.swing.JLabel priceText;
    private javax.swing.JTextField quantityFldText;
    private javax.swing.JLabel quantityText;
    private javax.swing.JPanel returnBtn;
    private javax.swing.JLabel returnBtnText;
    private javax.swing.JTextField sizeFldText;
    private javax.swing.JLabel sizeText;
    // End of variables declaration//GEN-END:variables
}
