/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ec.espe.edu.AirlineReservationSystem.view;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;

/**
 *
 * @author Joffre
 */
public class AdministratorPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdministratorPanel
     */
    public AdministratorPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Bg = new javax.swing.JPanel();
        addFlights = new javax.swing.JButton();
        addUsuarios = new javax.swing.JButton();
        addTickets = new javax.swing.JButton();
        datePanel = new javax.swing.JPanel();
        Equipajetxt = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fondoImage = new javax.swing.JLabel();

        Bg.setBackground(new java.awt.Color(255, 255, 255));

        addFlights.setBackground(new java.awt.Color(153, 153, 255));
        addFlights.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        addFlights.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/espe/airlinereservationsystem/images/vuelo-directo.png"))); // NOI18N
        addFlights.setText("Mostrar  Vuelos");
        addFlights.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFlightsActionPerformed(evt);
            }
        });

        addUsuarios.setBackground(new java.awt.Color(153, 153, 255));
        addUsuarios.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        addUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/espe/airlinereservationsystem/images/user icon.jpg"))); // NOI18N
        addUsuarios.setText("Mostrar Usuarios");
        addUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUsuariosActionPerformed(evt);
            }
        });

        addTickets.setBackground(new java.awt.Color(153, 153, 255));
        addTickets.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        addTickets.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/espe/airlinereservationsystem/images/ticket.png"))); // NOI18N
        addTickets.setText("Mostrar Tickets ");
        addTickets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTicketsActionPerformed(evt);
            }
        });

        datePanel.setBackground(new java.awt.Color(102, 0, 102));
        datePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Equipajetxt.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Equipajetxt.setForeground(new java.awt.Color(255, 255, 255));
        Equipajetxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Equipajetxt.setText("Administración");
        datePanel.add(Equipajetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 78));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/espe/airlinereservationsystem/images/fondo.jpeg"))); // NOI18N
        datePanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 110));

        fondoImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/espe/airlinereservationsystem/images/fondo.jpeg"))); // NOI18N
        datePanel.add(fondoImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 120));

        javax.swing.GroupLayout BgLayout = new javax.swing.GroupLayout(Bg);
        Bg.setLayout(BgLayout);
        BgLayout.setHorizontalGroup(
            BgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BgLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(addFlights, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125))
            .addGroup(BgLayout.createSequentialGroup()
                .addComponent(datePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(BgLayout.createSequentialGroup()
                .addGap(272, 272, 272)
                .addComponent(addTickets, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BgLayout.setVerticalGroup(
            BgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BgLayout.createSequentialGroup()
                .addComponent(datePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(BgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addFlights, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(addTickets, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Bg, javax.swing.GroupLayout.PREFERRED_SIZE, 920, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addTicketsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTicketsActionPerformed
        FrmAdTickets frmAddTickets = new FrmAdTickets();

        frmAddTickets.setSize(920, 500);
        frmAddTickets.setLocationRelativeTo(null); 
        this.setVisible(false);
        frmAddTickets.setVisible(true);

        frmAddTickets.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frmAddTickets.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent windowEvent) {
                AdministratorPanel.this.setVisible(true);
            }
        });
    }//GEN-LAST:event_addTicketsActionPerformed

    private void addFlightsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFlightsActionPerformed
        FrmAdFlights frmAdd = new FrmAdFlights();
        frmAdd.setSize(920, 600);
        frmAdd.setLocationRelativeTo(null); 
        this.setVisible(false);
        frmAdd.setVisible(true);

        frmAdd.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frmAdd.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent windowEvent) {
                AdministratorPanel.this.setVisible(true);
            }
        });
    }//GEN-LAST:event_addFlightsActionPerformed

    private void addUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUsuariosActionPerformed
        FrmAdUsuarios frmAddUsuarios = new FrmAdUsuarios();
        frmAddUsuarios.setSize(920, 600);
        frmAddUsuarios.setLocationRelativeTo(null);
        this.setVisible(false);
        frmAddUsuarios.setVisible(true);

        frmAddUsuarios.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frmAddUsuarios.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent windowEvent) {
                AdministratorPanel.this.setVisible(true);
            }
        });
      }//GEN-LAST:event_addUsuariosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Bg;
    private javax.swing.JLabel Equipajetxt;
    private javax.swing.JButton addFlights;
    private javax.swing.JButton addTickets;
    private javax.swing.JButton addUsuarios;
    private javax.swing.JPanel datePanel;
    private javax.swing.JLabel fondoImage;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
