/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.espe.edu.AirlineReservationSystem.view;

import ec.espe.edu.AirlineReservationSystem.controller.FlightController;
import ec.espe.edu.AirlineReservationSystem.controller.TicketController;
import ec.espe.edu.AirlineReservationSystem.model.Flight;
import ec.espe.edu.AirlineReservationSystem.model.Ticket;
import ec.espe.edu.AirlineReservationSystem.view.PayMethod;
import java.awt.Color;
import java.awt.HeadlessException;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Miguel Caiza,Overnight Developers Squad,DCCO-ESPE
 */
public class FrmTicket extends javax.swing.JFrame {

    /**
     * Creates new form FrmTickry
     */
    public FrmTicket() {
        initComponents();
    }
public JPanel GetBgTicket (){
    return jPanel1;
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ticketTitle = new javax.swing.JLabel();
        ticketsNumberLbl = new javax.swing.JLabel();
        ticketsNumberSpn = new javax.swing.JSpinner();
        jSeparator1 = new javax.swing.JSeparator();
        userLbl = new javax.swing.JLabel();
        userNameTxt = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        flightIdLbl = new javax.swing.JLabel();
        flightIdTxt = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        classTxt = new javax.swing.JLabel();
        classBox = new javax.swing.JComboBox<>();
        buyBtn = new javax.swing.JToggleButton();
        btnBack = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ticketTitle.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        ticketTitle.setForeground(new java.awt.Color(255, 255, 255));
        ticketTitle.setText("Compra de Boletos");
        jPanel1.add(ticketTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 550, 60));

        ticketsNumberLbl.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        ticketsNumberLbl.setText("Cantidad de Boletos : ");
        jPanel1.add(ticketsNumberLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 230, 20));

        ticketsNumberSpn.setBorder(null);
        jPanel1.add(ticketsNumberSpn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 70, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 210, 210, 10));

        userLbl.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        userLbl.setText("Nombre del Cliente :");
        jPanel1.add(userLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, -1, 20));

        userNameTxt.setBorder(null);
        userNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameTxtActionPerformed(evt);
            }
        });
        jPanel1.add(userNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 190, 210, 20));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 70, 10));

        flightIdLbl.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        flightIdLbl.setText("ID de vuelo :");
        jPanel1.add(flightIdLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, -1, 20));

        flightIdTxt.setBorder(null);
        flightIdTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flightIdTxtActionPerformed(evt);
            }
        });
        jPanel1.add(flightIdTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 150, 20));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 150, 10));

        classTxt.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        classTxt.setText("Clase :");
        jPanel1.add(classTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 290, -1, 20));

        classBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Economica", "Ejecutiva", " " }));
        classBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classBoxActionPerformed(evt);
            }
        });
        jPanel1.add(classBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 280, 100, 30));

        buyBtn.setBackground(new java.awt.Color(157, 117, 185));
        buyBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buyBtn.setForeground(new java.awt.Color(255, 255, 255));
        buyBtn.setText("REALIZAR PAGO");
        buyBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buyBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buyBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buyBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buyBtnMouseExited(evt);
            }
        });
        buyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyBtnActionPerformed(evt);
            }
        });
        jPanel1.add(buyBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, 200, 40));

        btnBack.setBackground(new java.awt.Color(157, 117, 185));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("REGRESAR");
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBackMouseExited(evt);
            }
        });
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 420, 140, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/espe/airlinereservationsystem/images/fondo.jpeg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 120));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 920, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buyBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buyBtnMouseClicked

    }//GEN-LAST:event_buyBtnMouseClicked

    private void buyBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buyBtnMouseEntered
        buyBtn.setBackground(new Color(173, 129, 204));
    }//GEN-LAST:event_buyBtnMouseEntered

    private void buyBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buyBtnMouseExited
        buyBtn.setBackground(new Color(157, 117, 185));
    }//GEN-LAST:event_buyBtnMouseExited

    private void buyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyBtnActionPerformed
      
try {
        int ticketNumber = (int) ticketsNumberSpn.getValue();
        String customerName = userNameTxt.getText().trim();
        String flightId = flightIdTxt.getText().trim();
        String ticketClass = classBox.getSelectedItem().toString().trim();

        if (ticketNumber == 0 || customerName.isEmpty() || flightId.isEmpty() || ticketClass.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!customerName.matches("[A-Za-z ]+")) {
            JOptionPane.showMessageDialog(this, "El nombre solo puede contener letras y espacios.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!flightId.matches("\\d+")) {
            JOptionPane.showMessageDialog(this, "El ID del vuelo solo puede contener dígitos.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Ticket ticket = new Ticket(ticketNumber, customerName, Integer.parseInt(flightId), ticketClass);
        
        TicketController ticketController = new TicketController();
        String ticketId = ticketController.saveTicket(ticket);
        
        if (ticketId != null) {
           JOptionPane.showMessageDialog(this,
    "<html><body style='width: 300px;'>"
    + "<p style='font-size: 14px;'>Ha reservado con exito su/s Ticket/s.</p>"
    + "<p style='font-size: 14px;'>El ID de su boleto es: <strong>" + ticketId + "</strong></p>"
    + "<p style='font-size: 14px;'>Por favor, proceda con el pago.</p>"
    + "</body></html>",
    "Éxito",
    JOptionPane.INFORMATION_MESSAGE);
            
            PayMethod payMethodDialog = new PayMethod();
       
        payMethodDialog.setLocationRelativeTo(null); 
        payMethodDialog.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Error al guardar el boleto en la base de datos.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        clearFields();

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Número de boleto o ID de vuelo no válido: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al registrar el ticket: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
}
    private void clearFields() {
    ticketsNumberSpn.setValue(0);
    userNameTxt.setText("");
    flightIdTxt.setText("");
    classBox.setSelectedIndex(0);

    }//GEN-LAST:event_buyBtnActionPerformed

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackMouseClicked

    private void btnBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackMouseEntered

    private void btnBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackMouseExited

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        FrmAirlineReservationSystem frmAirlineReservationSystem = new FrmAirlineReservationSystem();
        this.setVisible(false);
        frmAirlineReservationSystem.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void userNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameTxtActionPerformed

    private void flightIdTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flightIdTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_flightIdTxtActionPerformed

    private void classBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_classBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTicket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnBack;
    private javax.swing.JToggleButton buyBtn;
    private javax.swing.JComboBox<String> classBox;
    private javax.swing.JLabel classTxt;
    private javax.swing.JLabel flightIdLbl;
    private javax.swing.JTextField flightIdTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel ticketTitle;
    private javax.swing.JLabel ticketsNumberLbl;
    private javax.swing.JSpinner ticketsNumberSpn;
    private javax.swing.JLabel userLbl;
    private javax.swing.JTextField userNameTxt;
    // End of variables declaration//GEN-END:variables
}
